# -*- coding: utf-8 -*-
"""automatizacaoEmailPythonEnvio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-lSlbpGA0CMxhoqHSBkVySoRsddDsdbw
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

#Connection data
username = "your email here"
password = "your password here"

#Email information to send
rec = "recipient's email here"
subjectemail = "here"
textemail = "here"

#Message configuration
message = MIMEMultipart ()
message["From"] = username
message["To"] = rec
message["Subject"] = subjectemail
message.attach( MIMEText(textemail, "plain") )

#Sending the email
try:
  with smtplib.SMTP("smtp.gmail.com",587) as server :
    server.starttls()
    server.login(username,password)
    server.sendmail(username, rec, message.as_string() )
  print("Email successfully sent")
except Exception as e:
  print("Error sending the e-mail" + e)