# -*- coding: utf-8 -*-
"""automatizacaoEmailPythonLeitura.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ypqVIlHijG0tjjH1lAI5R1bEI1hc2ZkM
"""

!pip install imap_tools

#from the imap_tools library import the MailBox
from imap_tools import MailBox, A

username = "your email here"
password = "your password here"

#MailBox accesses Google server for login (main box)
acessEmail = MailBox("imap.gmail.com").login(username,password,"INBOX")

#listEmails is the same as accessing the email and presenting (email search engine) A=function from the imap_tools library
listEmails = acessEmail.fetch(A(from_="email to read"))

#for an email in listEmails: show the sender of the email
for email in listEmails:
  print(email.from_)
#subject is the same as email title
  print(email.subject)
  print(email.text)